### ISSUE TITLE
Missing features are reference line & series Synchronization

### ISSUE THREAD

**Issue by iconsys** [cornerstonejs/cornerstone3D-beta#105]
Two of the very important missing features in Cornerstone3D compared to earlier version are reference line & series synchronization (scroll).

**Comment by sedghi** [comment]
Thanks for the feedback. Yes, reference lines are missing currently, but we have synchronization (camera pan, zoom, scroll) for the VolumeViewport, and camera pan, zoom for StackViewport. Scrolling for Stack synchronizations is a tricky one since stacks can have completely different images.

Check out this demo https://www.cornerstonejs.org/live-examples/volumeviewportsynchronization

**Comment by sedghi** [comment]
this has been added to the library
