### ISSUE TITLE
Render vtkVolume without clipping

### ISSUE THREAD

**Issue by yonvaida** [cornerstonejs/cornerstone3D-beta#197]
Is there a solution to render in volume viewport a volume without creating clipping planes?

**Comment by sedghi** [comment]
The early version of Cornerstone3D was that way, by manipulating the camera clipping range (not clipping plane). But since we needed to implement non-image vtk [actors](https://www.cornerstonejs.org/live-examples/polydataactormanipulationtools) we had to embrace the clipping planes (which is better performance wise too).

What is your usecase where you don't want clipping planes?

**Comment by yonvaida** [comment]
I want to show whole volume in view like this view.
![image](https://user-images.githubusercontent.com/5926211/188568170-1fbbd0c6-f6be-48e9-a394-cf201943d5e9.png)
I remove cliping planes from volume Viewport and this is the result.

**Comment by sedghi** [comment]
and what should be the expected result?

**Comment by sedghi** [comment]
No there is no other method. Our VolumeViewport is currently an MPR viewport, so it has clipping planes. It has a Perspective for [polyData actors](https://www.cornerstonejs.org/live-examples/polydataactormanipulationtools).

For "real" 3D Viewport we need another type which is not implemented yet, but seems like you have got it working

**Comment by sedghi** [comment]
I'll close this since we added the new volume_3d viewport
