### ISSUE TITLE
Some questions about VolumeRotateMouseWheelTool

### ISSUE THREAD

**Issue by abluobo** [cornerstonejs/cornerstone3D-beta#286]
1. Bind mouseButton through setToolActive method, but it has no effect. Is it because VolumeRotateMouseWheelTool can only be operated through MouseWheel?
![image](https://user-images.githubusercontent.com/72963274/200785953-cb1b9794-5edb-4d19-8459-6df455c0f81b.png)
2. Whether a method similar to createVOISynchronizer is provided to realize simultaneous rotation of three faces of the image, because the VolumeRotateMouseWheelTool method can only rotate a single image
`const voiSynchronizer = createVOISynchronizer(ctVoiSynchronizerId);`

**Comment by sedghi** [comment]
1. VolumeRotateMouseWheel is not what you think it is. You can try it here in the MIP viewport on the right https://v3-demo.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463 I don't think we have a general volumeRotate that can work on the mouse yet, but it is not hard to implement. If you start something and create a PR I can guide you towards the implementation

2. That is an interesting use case, hmmmm, the cameraSynchronizer should handle your use case, since any volume rotate is basically rotating the camera

**Comment by abluobo** [comment]
Thank you for your answer！
There are three methods for synchronizers, as shown in the figure below. I can't find what you call "cameraSynchronizer".
If you mean the createCameraPositionSynchronizer, I have tried it. Three faces of the image can be synchronized, but the same face is displayed.

![image](https://user-images.githubusercontent.com/72963274/201027340-c410ad07-19f2-45f0-ab8a-f06084c79fc6.png)

**Comment by sedghi** [comment]
> Three faces of the image can be synchronized, but the same face is displayed.

What do you mean by this?

**Comment by abluobo** [comment]
In the MPR scene, when I rotate the transverse plane through the VolumeRotateMouseWheelTool method, the sagittal plane and the coronal plane can also rotate at the same time. Do you provide methods to achieve this effect?
![image](https://user-images.githubusercontent.com/72963274/201255872-685f43b7-61d5-4ceb-9f7a-03055e0b5c61.png)

**Comment by sedghi** [comment]
Sorry but still I'm not sure what you are asking here. Are you looking for a tool, that when used on a viewport to rotate camera, other viewports rotate or don't rotate?

**Comment by abluobo** [comment]
In the MPR scene，I used VolumeRotateMouseWheelTool, I used VolumeRotateMouseWheelTool  on a viewport to rotate camera，but other viewports don't rotate. I want to know how when I  used VolumeRotateMouseWheelTool  on a viewport to rotate camera, other viewports rotate at the same time.

**Comment by abluobo** [comment]
I recorded a gif animation to supplement my problems

![9mj64-likt5](https://user-images.githubusercontent.com/72963274/201512711-5c6227e1-211f-4097-8b8e-28bb81d1cb8f.gif)

**Comment by swederik** [comment]
Aha I see. So the tool currently rotates the camera viewUp around the
viewPlane normal, and it only does it within the viewport. What you want is
to rotate the actual volume orientation inside the world space so that it's
reflected in all viewports. You can change the orientation matrix for the
volume to do this, but it would be a separate tool.
