### ISSUE TITLE
load nifti as a volume

### ISSUE THREAD

**Issue by MYWpro** [cornerstonejs/cornerstone3D-beta#428]
Can I directly load nifti as a volume? Do I have to convert the format to dicom to load nifti?

**Comment by sedghi** [comment]
Stay tuned, we are adding it soon. Development is done

**Comment by MYWpro** [comment]
#311 Thank you for your hard work, I still have a question, can the updated content be able to save the modified segmentation to the local in nifti format

**Comment by sedghi** [comment]
Yes it would be possible

**Comment by MYWpro** [comment]
Will the loading function be added this month? I'm looking forward to it.

**Comment by MYWpro** [comment]
Hello, I'm sorry to bother you. I want to know whether Cornerstone3d support for the nifti format will be updated this month. Because I have an application that needs to use the nifti format and needs to be completed at the beginning of next month, can you tell me whether it will be updated?

> Stay tuned, we are adding it soon. Development is done

**Comment by acegank** [comment]
more than three months have passed

**Comment by sedghi** [comment]
yeah I guess I shouldn't give definite times since priorities change, but we are releasing the new roadmap soon

**Comment by adconk** [comment]
hi @sedghi, do you know the status of nifti-volume-loading? I'm part of another interested party. Thx!

**Comment by Valar-hub** [comment]
I implement the function to load nifti as a volume by modify the by modifying a little of 'cornerstoneStreamingImageVolumeLoader.js' source code. But i'm busy for a short period of time. I can give some tips to implement it by modifying 'cornerstoneStreamingImageVolumeLoader.js' source code:1. change to image loader to the old 'nifti-image-loader' for legacy cornerstone. 2. nifti is not needed to calculate the zspace and resort the position,beacuse it's 3d, so we can just avoid this function-'sortImageIdsAndGetSpacing' from './helpers'. 3. nifti can get metaData from file instead of http request from web, so we use old 'nifti-image-loader' for legacy cornerstone to get metaData. In summary, we try to use the old API to deal the nifti file as 2D sequence,  but maybe it is not enough efficent.

**Comment by Valar-hub** [comment]
I implement the function to load nifti as a volume by modifying a little of 'cornerstoneStreamingImageVolumeLoader.js' source code. But i'm too busy to give a detailed code for a short period of time. I can give some tips to implement it by modifying 'cornerstoneStreamingImageVolumeLoader.js' source code:1. change to image loader to the old 'nifti-image-loader' for legacy cornerstone. 2. nifti is not needed to calculate the zspace and resort the position,beacuse it's 3d, so we can just avoid this function-'sortImageIdsAndGetSpacing' from './helpers'. 3. nifti can get metaData from file instead of http request from web, so we use old 'nifti-image-loader' for legacy cornerstone to get metaData. In summary, we try to use the old API to deal the nifti file as 2D sequence, but maybe it is not enough efficent.

**Comment by sedghi** [comment]
I have a branch that has the preliminary work [here](https://github.com/cornerstonejs/cornerstone3D/tree/feat/nifti-loader), I will create a PR later. There are two new examples

**Comment by sedghi** [comment]
track here https://github.com/cornerstonejs/cornerstone3D/pull/696
